package Practice;

public class COnvertJson {
    public static void main(String[] args) {
        String sample = "Residence_Occupancy_Status	Govt. Accomodation\r\n"
        		+ "Residence_In_Present_House	45\r\n"
        		+ "Residence_In_Present_Area	45\r\n"
        		+ "Residency_Type	Flat\r\n"
        		+ "No_of_floors	6\r\n"
        		+ "Size_In_Sq.ft	1000\r\n"
        		+ "Total_No_of_Floors	6\r\n"
        		+ "Roof_Type	Tilled\r\n"
        		+ "Access_To_Residence	Difficult To Access\r\n"
        		+ "Remark	Residence Verification \r\n"
        		+ "Relationship_with_MainApplicant	SON\r\n"
        		+ "Age	13\r\n"
        		+ "Mobile_Number	9876543234\r\n"
        		+ "Qualification	Graduate\r\n"
        		+ "Status	Studying\r\n"
        		+ "Rent	10000\r\n"
        		+ "Mobile	7000\r\n"
        		+ "Food	3000\r\n"
        		+ "Travel_Expense	2500\r\n"
        		+ "Education	6000\r\n"
        		+ "Misc	1000\r\n"
        		+ "Name_of_Neighbour	Oppenheimer\r\n"
        		+ "Address_1	Indiqube South Summit\r\n"
        		+ "Address_2	South end circle\r\n"
        		+ "Village	Tikar B.O\r\n"
        		+ "Relationship_with_Customer	Good\r\n"
        		+ "Applicant's_Business_Daily_Foot_Fall	Low\r\n"
        		+ "Final_Verification_Status	Positive\r\n"
        		+ "Designation	Pensioner\r\n"
        		+ "Organization_Name	TestYantra\r\n"
        		+ "Address_Same_As	Banshawaliyon Ka Gurha RAJSAMAND RAJSAMAND\r\n"
        		+ "Additional documents	Bank details\r\n"
        		+ "PD_Category	Bank Account\r\n"
        		+ "Udyam_Name	Meera R\r\n"
        		+ "Industry_Category	Agri - Rice Mill\r\n"
        		+ "Investment_In_Plant_and_Machine	200000\r\n"
        		+ "Yearly_Income	600000\r\n"
        		+ "Udyam_Number_Is_Avialable	Yes\r\n"
        		+ "Udyam_Number	UDYAM-MH-23-1287887\r\n"
        		+ "Applicant_Type	Applicant\r\n"
        		+ "Applicant_Name	MEERA ASOPA R\r\n"
        		+ "IFSC	UTIB0001496\r\n"
        		+ "A/c_Holder_Name	Meera\r\n"
        		+ "A/c_Number	98765434567\r\n"
        		+ "Account_Type	Savings\r\n"
        		+ "Net_Banking	Yes\r\n"
        		+ "Account_Function_Type	Repayment Account Only\r\n"
        		+ "Document_Category	Bank Related Documents\r\n"
        		+ "Document_Type	Bank Statement\r\n"
        		+ "Name_of_Reference	chandan\r\n"
        		+ "Type_of_Interaction	Call Centre Lead\r\n"
        		+ "Know_Customer_Since	4\r\n"
        		+ "Purchase_Vloume_In_Last_3_Months	200000\r\n"
        		+ "No_of_delay_In_Payments_In_Last_6Months	10\r\n"
        		+ "Credit_Facility_Available	Yes\r\n"
        		+ "Credit_Period	5\r\n"
        		+ "Monthly_Sales_Basis_Suppliers_Feedback	Reference\r\n"
        		+ "Supplier_Check_status	Positive\r\n"
        		+ "Feedback_On_Finanacial_Stability	Finance\r\n"
        		+ "Name_of_the_Owner_of_the_property	Meera R\r\n"
        		+ "Land_Mark	Opposite to South end circle metro station\r\n"
        		+ "Building_Types	8\r\n"
        		+ "Type_of_Property	Residential\r\n"
        		+ "Collateral_Type	Flat\r\n"
        		+ "Area_In_Sq_Ft	1000\r\n"
        		+ "Survey_Number	5678\r\n"
        		+ "Access_To_Address	Difficult To Access\r\n"
        		+ "Collateral_Authority	Gram Panchayat\r\n"
        		+ "Construction_Stage	55\r\n"
        		+ "Market_Value	98760\r\n"
        		+ "How_much_is_Self_Occupied	65\r\n"
        		+ "How_nuch_given_on_Rent	55\r\n"
        		+ "Boundary_remarks_North	No remarks\r\n"
        		+ "Boundary_remarks_South	No remarks\r\n"
        		+ "Boundary_remarks_East	No remarks\r\n"
        		+ "Boundary_remarks_West	No remarks\r\n"
        		+ "Land_Area_Rate_Per_Sq.ft	2300\r\n"
        		+ "Constructed_Area_Rate_Per_Sq.ft	3456\r\n"
        		+ "Collateral_Document_Category	Collateral Documents\r\n"
        		+ "Collateral_Document_Type	Electricity Bill\r\n"
        		+ "PD_Details	PD details\r\n"
        		+ "Location_Type	Branch\r\n"
        		+ "Location_Name	Fetahnagar\r\n"
        		+ "Property_On_Agricultural_Land	Yes\r\n"
        		+ "Vendor_Name	kiran dadagiri\r\n"
        		+ "Property_Age	5\r\n"
        		+ "Residual_Age	7\r\n"
        		+ "Land_Area	800\r\n"
        		+ "Build_Up_Area	1000\r\n"
        		+ "Price_Per_Square_Feet	2300\r\n"
        		+ "Plot_Value	400\r\n"
        		+ "Land_Cost	100000\r\n"
        		+ "Construction_Estimate	250000\r\n"
        		+ "Cost_of_Purchase	300000\r\n"
        		+ "F_and_F_Agreement	65000\r\n"
        		+ "Stamp_Duty_And_Registration_Charges	2000\r\n"
        		+ "Other_Charges	1000\r\n"
        		+ "Cost_of_Property	234000\r\n"
        		+ "Market_Value	250000\r\n"
        		+ "Entity_Type	Individual\r\n"
        		+ "High_Risk_Business	No\r\n"
        		+ "Country_of_Incorporation	India\r\n"
        		+ "Primary_Country_of_Operations	India\r\n"
        		+ "FATF_list_Countries	NA\r\n"
        		+ "Any_ShareHolder_Domiciled_Countries	NA\r\n"
        		+ "Multiple_Product_Offered	No\r\n"
        		+ "Regualr_Interface_with_Entity	Physical / Face - to - Face\r\n"
        		+ "Visit_To_Place_of_business_conducted	Yes\r\n"
        		+ "Was_Visit_Satisifactory	Yes\r\n"
        		+ "Origin_of_Health	NA\r\n"
        		+ "Politically_Exposed_Person	No\r\n"
        		+ "Sanctions_Found	No\r\n"
        		+ "Undergoing_Any_Medication	No\r\n"
        		+ "Undergone_Any_Surgery_In_last_3years	No\r\n"
        		+ "Major_Illness	No\r\n"
        		+ "SBL	40\r\n"
        		+ "Policy_Multiplier	1\r\n"
        		+ "Obbligation	0\r\n"
        		+ "ROI	25\r\n"
        		+ "TENOR	96\r\n"
        		+ "Scheme	SBL(P) Upto 8 Lakhs\r\n"
        		+ "Disbursement_Date	Fully Disbursed\r\n"
        		+ "Due_Date	4\r\n"
        		+ "Repayment_Mode	DEMAND DRAFT\r\n"
        		+ "Life_Insurance	ICICI Prudential Insurance\r\n"
        		+ "Property_Insurance	GO DIGIT\r\n"
        		+ "Insurance_Applicant_Name	Nayana H N\r\n"
        		+ "Nominee_First_Name	Naina\r\n"
        		+ "Nominee_Last_Name	H N\r\n"
        		+ "Nominee_Gender	Male\r\n"
        		+ "Nominee_Relationship	SON";
        
        String[] lines = sample.split("\n");
        StringBuilder jsonBuilder = new StringBuilder("{");
        for (String line : lines) {
            String[] parts = line.split("\t", 2);
            jsonBuilder.append("\"").append(parts[0]).append("\":\"").append(parts[1]).append("\",");
        }

        jsonBuilder.deleteCharAt(jsonBuilder.length() - 1);
        jsonBuilder.append("}");
        String json = jsonBuilder.toString();
        System.out.println(json);
        
    }
}

